// GP Sim portrait: photoreal patient built from a stack of stills.
//
//   setExpression(name)  neutral | worried | pain | relieved
//   setViseme(name)      closed | half | open | wide | round
//   stopSpeaking()       return to a closed mouth
//
// Every frame is preloaded and stacked absolutely; "animation" is a fast
// crossfade between frames. Frames must share identical framing and lighting
// (generated by editing one hero image) or the crossfade visibly jumps.
//
// Mouth shapes are the five that carry English speech: closed (m/b/p),
// half (most consonants), open (ah), wide (ee), round (oh/oo). Expressions
// missing a shape fall back to their closed frame, so a partial set still
// works — `pain` is deliberately closed-only, being a brief reaction.

const FRAMES = {
    neutral: {
        closed: 'portraits/margaret-neutral-closed.jpg',
        half: 'portraits/margaret-neutral-half.jpg',
        open: 'portraits/margaret-neutral-open.jpg',
        wide: 'portraits/margaret-neutral-wide.jpg',
        round: 'portraits/margaret-neutral-round.jpg',
    },
    worried: {
        closed: 'portraits/margaret-worried-closed.jpg',
        half: 'portraits/margaret-worried-half.jpg',
        open: 'portraits/margaret-worried-open.jpg',
        wide: 'portraits/margaret-worried-wide.jpg',
        round: 'portraits/margaret-worried-round.jpg',
    },
    relieved: {
        closed: 'portraits/margaret-relieved-closed.jpg',
        half: 'portraits/margaret-relieved-half.jpg',
        open: 'portraits/margaret-relieved-open.jpg',
        wide: 'portraits/margaret-relieved-wide.jpg',
        round: 'portraits/margaret-relieved-round.jpg',
    },
    pain: {
        closed: 'portraits/margaret-pain-closed.jpg',
    },
};

// Visemes arrive every ~80-150ms; this only guards against absurd flicker.
const MIN_FRAME_MS = 45;

export function createPortrait(container) {
    container.innerHTML = '';
    container.classList.add('portrait-photo');

    // The stage carries the CSS breathing animation; the inner element exists
    // so nothing else has to fight that animation for the transform property.
    const stage = document.createElement('div');
    stage.className = 'portrait-stage';
    const inner = document.createElement('div');
    inner.className = 'portrait-inner';
    stage.appendChild(inner);
    container.appendChild(stage);

    const layers = new Map();
    for (const frames of Object.values(FRAMES)) {
        for (const src of Object.values(frames)) {
            if (layers.has(src)) continue;
            const img = document.createElement('img');
            img.src = src;
            img.alt = '';
            img.decoding = 'async';
            img.className = 'portrait-layer';
            inner.appendChild(img);
            layers.set(src, img);
        }
    }

    let expression = 'neutral';
    let viseme = 'closed';
    let pendingViseme = 'closed';
    let lastSwapAt = 0;
    let visibleSrc = null;

    function show(src) {
        if (src === visibleSrc) return;
        layers.forEach((img, key) => { img.style.opacity = key === src ? '1' : '0'; });
        visibleSrc = src;
    }

    function render() {
        const set = FRAMES[expression] || FRAMES.neutral;
        show(set[viseme] || set.closed);
    }

    function updateAlt() {
        const first = layers.get((FRAMES[expression] || FRAMES.neutral).closed);
        if (first) first.alt = `Margaret Hughes, looking ${expression}`;
    }

    show(FRAMES.neutral.closed);
    updateAlt();

    return {
        setExpression(name) {
            if (!FRAMES[name] || name === expression) return;
            expression = name;
            updateAlt();
            render();
        },

        setViseme(name) {
            pendingViseme = name;
            if (name === viseme) return;
            const now = performance.now();
            if (now - lastSwapAt < MIN_FRAME_MS) return;
            viseme = name;
            lastSwapAt = now;
            render();
        },

        stopSpeaking() {
            viseme = 'closed';
            pendingViseme = 'closed';
            render();
        },
    };
}
