// GP Sim portrait: photoreal patient built from a stack of stills.
//
// Same public interface as the vector portrait it replaced, so nothing else in
// the app changed:
//   setExpression(name)  neutral | worried | pain | relieved
//   setMouth(amp)        0..1 live audio amplitude → mouth frame
//   stopSpeaking()       return to a closed mouth
//
// Every frame is preloaded and stacked absolutely; "animation" is a fast
// crossfade between frames. Frames must share identical framing and lighting
// (generated by editing one hero image) or the crossfade visibly jumps.
//
// Expressions that have no mouth frames yet fall back to their closed frame
// plus a subtle amplitude-driven scale, so speech still reads as movement.
// Add the files and list them here and they animate properly — no other change.

const FRAMES = {
    neutral: {
        closed: 'portraits/margaret-neutral-closed.jpg',
        half: 'portraits/margaret-neutral-half.jpg',
        open: 'portraits/margaret-neutral-open.jpg',
    },
    worried: {
        closed: 'portraits/margaret-worried.jpg',
    },
    pain: {
        closed: 'portraits/margaret-pain.jpg',
    },
    relieved: {
        closed: 'portraits/margaret-relieved.jpg',
    },
};

// Amplitude thresholds with a gap between them (hysteresis) so a voice hovering
// near a boundary doesn't strobe between two frames.
const OPEN_ON = 0.46, OPEN_OFF = 0.34;
const HALF_ON = 0.15, HALF_OFF = 0.09;
const MIN_FRAME_MS = 70; // never swap frames faster than this

export function createPortrait(container) {
    container.innerHTML = '';
    container.classList.add('portrait-photo');

    const stage = document.createElement('div');
    stage.className = 'portrait-stage';
    container.appendChild(stage);

    // One <img> per unique file, preloaded and stacked.
    const layers = new Map();
    for (const frames of Object.values(FRAMES)) {
        for (const src of Object.values(frames)) {
            if (layers.has(src)) continue;
            const img = document.createElement('img');
            img.src = src;
            img.alt = '';
            img.decoding = 'async';
            img.className = 'portrait-layer';
            stage.appendChild(img);
            layers.set(src, img);
        }
    }

    let expression = 'neutral';
    let mouth = 'closed';
    let smoothed = 0;
    let lastSwapAt = 0;
    let visibleSrc = null;

    function show(src) {
        if (src === visibleSrc) return;
        layers.forEach((img, key) => { img.style.opacity = key === src ? '1' : '0'; });
        visibleSrc = src;
    }

    // Resolve the frame for the current expression + mouth, falling back to the
    // expression's closed frame when that mouth state hasn't been generated.
    function render() {
        const set = FRAMES[expression] || FRAMES.neutral;
        const src = set[mouth] || set.closed;
        show(src);

        // Expressions with no mouth frames: fake a little life while speaking.
        const faked = !set[mouth] && mouth !== 'closed';
        stage.style.transform = faked
            ? `scale(${(1 + smoothed * 0.012).toFixed(4)})`
            : 'scale(1)';
    }

    // Alt text carries the patient's state for screen readers.
    function updateAlt() {
        const first = layers.get((FRAMES[expression] || FRAMES.neutral).closed);
        if (first) first.alt = `Margaret Hughes, looking ${expression}`;
    }

    show(FRAMES.neutral.closed);
    updateAlt();

    return {
        setExpression(name) {
            if (!FRAMES[name] || name === expression) return;
            expression = name;
            updateAlt();
            render();
        },

        setMouth(amp) {
            smoothed += (amp - smoothed) * 0.5;

            let next = mouth;
            if (smoothed >= OPEN_ON) next = 'open';
            else if (smoothed >= HALF_ON && mouth !== 'open') next = 'half';
            else if (mouth === 'open' && smoothed < OPEN_OFF) next = smoothed >= HALF_ON ? 'half' : 'closed';
            else if (mouth === 'half' && smoothed < HALF_OFF) next = 'closed';

            const now = performance.now();
            if (next !== mouth && now - lastSwapAt >= MIN_FRAME_MS) {
                mouth = next;
                lastSwapAt = now;
            }
            render();
        },

        stopSpeaking() {
            smoothed = 0;
            mouth = 'closed';
            render();
        },
    };
}
